apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${KUBE_NAMESPACE}
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: ${KUBE_NAMESPACE}
spec:
  # Scaled to 3 to allow for rolling update, on 24th June 25
  # See README.md section: 'Deployment to Cloud Platform'
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: ${KUBE_NAMESPACE}
  template:
    metadata:
      labels:
        app: ${KUBE_NAMESPACE}
    spec:
      volumes:
        - name: uploads
          emptyDir: { }
        - name: php-socket
          emptyDir: { }
      terminationGracePeriodSeconds: 35
      serviceAccountName: ${KUBE_NAMESPACE}-service
      containers:
        - name: nginx
          image: ${ECR_URL}:${IMAGE_TAG_NGINX}
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/public/app/uploads
            - name: php-socket
              mountPath: /sock
          securityContext:
            runAsUser: 101
          env:
            - name: IPS_FORMATTED
              valueFrom:
                secretKeyRef:
                  name: ${KUBE_NAMESPACE}-base64-secrets
                  key: IPS_FORMATTED

        - name: cron
          image: ${ECR_URL}:${IMAGE_TAG_CRON}
          resources:
            limits:
              cpu: 50m
              memory: 30Mi
            requests:
              cpu: 1m
              memory: 12Mi
          securityContext:
            runAsUser: 3001

        - name: fpm
          image: ${ECR_URL}:${IMAGE_TAG_FPM}
          resources:
            limits:
              cpu: "4"
              memory: 2000Mi
            requests:
              cpu: 500m
              memory: 600Mi
          volumeMounts:
            - name: uploads
              mountPath: /var/www/html/public/app/uploads
            - name: php-socket
              mountPath: /sock
          securityContext:
            runAsUser: 101
          env:
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket-output
                  key: bucket_name
            - name: AWS_CLOUDFRONT_PUBLIC_KEYS_OBJECT
              valueFrom:
                secretKeyRef:
                  name: cloudfront-output
                  key: cloudfront_public_keys
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-output
                  key: rds_instance_address
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-output
                  key: database_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-output
                  key: database_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-output
                  key: database_password
            - name: OPENSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: opensearch-output
                  key: proxy_url
            - name: BASIC_AUTH
              valueFrom:
                secretKeyRef:
                  name: basic-auth-secret
                  key: auth
            # This is the IP address of the pod, set by Kubernetes.
            # Pods on the network can use this IP to communicate with each other.
            # i.e. An nginx purge url can be created with http://<NGINX_IP>:8080/purge/<url>
            #      Purge urls for all pods, can be called from a single fpm container.
            # N.B. On Kubernetes, the IP address is the same for all containers in the pod,
            #      and the IP address assigned to a pod will never change once the pod is running.
            #      On Docker Compose, the hostname is the name of the service, and used instead of the IP address.
            - name: NGINX_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: ${KUBE_NAMESPACE}
            - secretRef:
                name: ${KUBE_NAMESPACE}-secrets
            - secretRef:
                name: ${KUBE_NAMESPACE}-base64-secrets
