version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:12"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "chore"
    groups:
      github-actions:
        patterns:
          - "*"
    assignees:
      - "hale-platform"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:24"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "chore"
    groups:
      docker-packages:
        patterns:
          - "*"
    assignees:
      - "hale-platform"

  - package-ecosystem: "npm"
    directory: "public/app/themes/clarity"
    schedule:
      interval: "daily"
      time: "00:36"
    cooldown:
      default-days: 3
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "chore"
    groups:
      npm-packages:
        patterns:
          - "*"
    assignees:
      - "hale-platform"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:42"
    cooldown:
      default-days: 3
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "chore"
    groups:
      composer-packages:
        patterns:
          - "*"
    assignees:
      - "hale-platform"
