#!/usr/bin/env node

/* GenReg v1.0.0
   Author: Alex Foxleigh (github.com/foxleigh81)
   Description: A tool to find all component.json files in the project and use them to generate
   a register of components.
   Usage: 'node genreg'
 */

 var glob = require('glob-fs')({ gitignore: true })
 var chalk = require('chalk')
 var fs = require('fs')

// A string containing the header for the component register
 var regHeader = '<!DOCTYPE html><html lang=en><head><meta charset=UTF-8><title>Clarity component register</title><link rel=stylesheet href=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css><style>body{padding:10px 10%}table{width:100%;margin-bottom:20px;border:1px solid #ccc;margin-top:20px}thead th{background-color:#ccc;padding:10px}tr:nth-child(even){background-color:#f4f4f4}td,th{padding:5px 10px}h1{margin-bottom:20px}</style></head> <body> <h1>Component Register</h1> <p>This document is a list of all of the components that the clarity theme currently has available. Please do not edit this file, it is generated automatically.</p> <table> <thead> <tr> <th>Component Name</th> <th>Latest version</th> <th>Creation ticket</th> <th>Author</th> <th>Description</th> <th>JS?</th> </tr> </thead> <tbody>'
// A string containing the footer for the component register
 var regFooter = '<p>Please note: This file relies on a component being correctly documented and may not be 100% accurate</p></tbody></table></body></html>'

// Loop through all the files in the component folder
 var getFiles = function () {
   var files = glob.readdirSync('src/components/**/component.json')
   var string = ''
   for (var i = 0; i < files.length; i++) {
     string = string + readFiles(files[i])
   }
   return string
 }
// Reach each file and pass the contents to createRows()
 var readFiles = function (file) {
   var obj = JSON.parse(fs.readFileSync(file, 'utf8'))
   return createRows(obj)
 }

// Generate a HMTL table row with all the component data
 var createRows = function (obj) {
   var jsStat = (obj.has_js) ? 'yes' : 'no'
   var hasTicket = (obj.creation_ticket) ? '<a href="https://dsdmoj.atlassian.net/browse/' + obj.creation_ticket + '">Jira Link</a>' : 'No ticket specified'
   return ('<tr><td>' + obj.name + '</td><td>' + obj.version + '</td><td>' + hasTicket + '</td><td><a href="http://github.com/' + obj.creator.github_username + '">' + obj.creator.name + '</a></td><td>' + obj.description + '</td><td>' + jsStat + '</td></tr>')
 }

// merge the header and footer with the data from getFiles()
 var createFile = function () {
   return regHeader + getFiles() + regFooter
 }

// Create the component-register file
 fs.writeFile('component-register.html', createFile(), function (err) {
   if (err) return console.log(chalk.red(err))
   console.log(chalk.green('Component register updated!'))
 })
