{
 "title": "Intranet Service",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_status_code_wp_home,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Control (gov.uk)",
   "type": "stat",
   "description": "The http status code when accessing an open site.\n\nThis should always be 200.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_status_code_control{namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "description": "The http status code of /health.\n\nThis should always be 200.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_status_code_health{namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home",
   "type": "stat",
   "description": "The http status code when accessing this service via it's full url as defined in WP_HOME.\n\nThis should be 200 or 401 depending on the namespace.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_status_code_wp_home{namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Invalid header",
   "type": "stat",
   "description": "The http status code of when sending X-Moj-Ip-Group header.\n\nThis should always be 400.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_status_code_invalid_header{namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stauts Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "http_status_code_health{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "http_status_code_wp_home{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "http_status_code_invalid_header{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "http_status_code_control{namespace=\"$namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}