apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: intranet-dev
  labels:
    app: intranet-dev
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: intranet-dev
---
apiVersion: v1
kind: Service
metadata:
  name: pod-broadcaster-service
  labels:
    app: intranet-dev-pod-broadcaster
spec:
  ports:
  - port: 1993
    name: http
  selector:
    app: intranet-dev-pod-broadcaster
