source 'https://rubygems.org'

ruby '2.5.1'

group :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'docker-api'
  gem 'hashie'
  gem 'launchy'
  gem 'poltergeist'
  gem 'phantomjs'
  gem 'pry'
  gem 'rest-client'
  gem 'rspec'
end
