apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: intranet-production
  namespace: intranet-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: intranet-production
  minReplicas: 4
  maxReplicas: 12
  metrics:
    # fpm
    - type: ContainerResource
      containerResource:
        name: cpu
        container: fpm
        target:
          type: Utilization
          # If request is 500m let's early scale at 250m
          # Rely on CPU usage for scaling more than memory usage.
          # For scaling down, CPU settles quickly and memory is freed up slowly.
          averageUtilization: 50
    - type: ContainerResource
      containerResource:
        name: memory
        container: fpm
        target:
          type: Utilization
          # If request is 640Mi and php max is 384Mi let's scale at 512Mi
          averageUtilization: 80
    # nginx
    - type: ContainerResource
      containerResource:
        name: cpu
        container: nginx
        target:
          type: Utilization
          averageUtilization: 60
    - type: ContainerResource
      containerResource:
        name: memory
        container: nginx
        target:
          type: Utilization
          averageUtilization: 70
