apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: intranet-production
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: intranet-production
---
apiVersion: v1
kind: Service
metadata:
  name: pod-broadcaster-service
  labels:
    app: intranet-production-pod-broadcaster
spec:
  ports:
  - port: 1993
    name: http
  selector:
    app: intranet-production-pod-broadcaster
