<?php

/**
 * Makes some changes to the <title> tag, by filtering the output of wp_title().
 *
 * If we have a site description and we're viewing the home page or a blog posts
 * page (when using a static front page), then we will add the site description.
 *
 * If we're viewing a search result, then we're going to recreate the title entirely.
 * We're going to add page numbers to all titles as well, to the middle of a search
 * result title and the end of all other titles.
 *
 * The site title also gets added to all titles.
 *
 * @since Twenty Ten 1.0
 *
 * @param string $title Title generated by wp_title()
 * @param string $separator The separator passed to wp_title(). Twenty Ten uses a
 *  vertical bar, "|", as a separator in header.php.
 * @return string The new title, ready for the <title> tag.
 */
function twentyten_filter_wp_title( $title, $separator ) {
  $site_name = get_bloginfo( 'name', 'display' );
  $title = $title ? "$title - $site_name" : $site_name;
  return trim(preg_replace('/\[.*\]/i', '', $title));
}

add_filter( 'wp_title', 'twentyten_filter_wp_title', 10, 2 );

function govintranetpress_custom_title( $output ) {
  if (!is_admin()) {
    return trim(preg_replace('/\[.*\]/i','',$output));
  } else {
    return $output;
  }
}
add_filter( 'the_title', 'govintranetpress_custom_title' );
