name: "CI Build"

on:
  workflow_call:
    outputs:
      registry:
        description: "AWS registry where the ECR is located"
        value: ${{ jobs.image_build.outputs.registry }}
    inputs:
      pipeline:
        description: 'Define the pipeline in use. One of main or qa'
        required: true
        default: 'main'
        type: string

jobs:
  image_build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.ecr-login.outputs.registry }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Comment PR to indicate build start"
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            The QA environment is being updated...
          comment-tag: to_delete_on_completion
          mode: delete-on-completion
          reactions: eyes

      - name: "Configuring AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - name: "Logging into ECR"
        uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login

      - name: "Build & Push to ECR"
        run: |
          
          # ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░
               
          docker image build -t $REGISTRY/$REPOSITORY:fpm-$IMAGE_TAG \
            -t $REGISTRY/$REPOSITORY:$PIPELINE_TAG \
            --build-arg ACF_PRO_LICENSE="$ACF_PRO_LICENSE" --build-arg ACF_PRO_PASS="$ACF_PRO_PASS"     \
            --build-arg AS3CF_PRO_USER="$AS3CF_PRO_USER"   --build-arg AS3CF_PRO_PASS="$AS3CF_PRO_PASS" \
            --build-arg IMAGE_TAG="$IMAGE_TAG" \
            --target build-fpm .
          
          docker image build -t $REGISTRY/$REPOSITORY:nginx-$IMAGE_TAG \
            -t $REGISTRY/$REPOSITORY:$PIPELINE_TAG \
            --build-arg ACF_PRO_LICENSE="$ACF_PRO_LICENSE" --build-arg ACF_PRO_PASS="$ACF_PRO_PASS"     \
            --build-arg AS3CF_PRO_USER="$AS3CF_PRO_USER"   --build-arg AS3CF_PRO_PASS="$AS3CF_PRO_PASS" \
            --target build-nginx .
          
          docker image build -t $REGISTRY/$REPOSITORY:cron-$IMAGE_TAG \
            -t $REGISTRY/$REPOSITORY:$PIPELINE_TAG \
            --target build-cron .

          docker image build -t $REGISTRY/$REPOSITORY:s3-push-$IMAGE_TAG \
            -t $REGISTRY/$REPOSITORY:$PIPELINE_TAG \
            --build-arg ACF_PRO_LICENSE --build-arg ACF_PRO_PASS   \
            --build-arg AS3CF_PRO_USER  --build-arg AS3CF_PRO_PASS \
            --build-arg IMAGE_TAG \
            --target build-s3-push .

          # ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░
          
          docker image push --all-tags $REGISTRY/$REPOSITORY:fpm-$IMAGE_TAG
          docker image push --all-tags $REGISTRY/$REPOSITORY:nginx-$IMAGE_TAG
          docker image push --all-tags $REGISTRY/$REPOSITORY:cron-$IMAGE_TAG
          docker image push --all-tags $REGISTRY/$REPOSITORY:s3-push-$IMAGE_TAG
          
          # ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░

        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          PIPELINE_TAG: ${{ github.events.inputs.pipeline }}
          ACF_PRO_LICENSE: ${{ secrets.ACF_PRO_LICENSE }}
          ACF_PRO_PASS: ${{ secrets.ACF_PRO_PASS }}
          AS3CF_PRO_USER: ${{ secrets.AS3CF_PRO_USER }}
          AS3CF_PRO_PASS: ${{ secrets.AS3CF_PRO_PASS }}
