name: Deploy to MoJ Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  image:
    name: "Image"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    secrets: inherit

  get_ip_ranges:
    name: "IP Ranges"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/ip-ranges-configure.yml
    permissions:
      contents: read
    secrets: inherit

  modsec_config:
    name: "Modsec"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/modsec-config.yml
    permissions:
      contents: read
    secrets: inherit

  deploy_dev:
    name: "Development"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: [image, get_ip_ranges, modsec_config]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
      ips_formatted: ${{ needs.get_ip_ranges.outputs.ips_formatted }}
      modsec_config: ${{ needs.modsec_config.outputs.development }}
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit

  deploy_staging:
    name: "Staging"
    needs: [image, deploy_dev, get_ip_ranges, modsec_config]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      registry: ${{ needs.image.outputs.registry }}
      ips_formatted: ${{ needs.get_ip_ranges.outputs.ips_formatted }}
      modsec_config: ${{ needs.modsec_config.outputs.staging }}
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit

  deploy_production:
    name: "Production"
    needs: [image, deploy_staging, get_ip_ranges, modsec_config]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
      ips_formatted: ${{ needs.get_ip_ranges.outputs.ips_formatted }}
      modsec_config: ${{ needs.modsec_config.outputs.production }}
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
