name: Deploy to QA Environment

on:
  pull_request:
    types:
      - converted_to_draft
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eligibility:
    name: Determine eligibility
    if: github.event.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      eligible: ${{ steps.eligible.outputs.result }}
    steps:
      - name: Get draft PRs
        id: get-draft-prs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "result=$(gh pr list --repo ministryofjustice/intranet --draft --state open --json number)" >> "$GITHUB_OUTPUT";
      - name: Verify PR status
        id: eligible
        uses: actions/github-script@v7
        with:
          script: |
            const draftPRs = JSON.parse('${{ steps.get-draft-prs.outputs.result }}').map( ( pr ) => pr.number );
            return !draftPRs.includes(${{
              github.event.pull_request.number
            }});

  image:
    name: "Image"
    needs: eligibility
    if: ${{ needs.eligibility.outputs.eligible == 'true' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit

  get_ip_ranges:
    name: "IP Ranges"
    needs: eligibility
    if: ${{ needs.eligibility.outputs.eligible == 'true' }}
    uses: ./.github/workflows/ip-ranges-configure.yml
    secrets: inherit

  modsec_config:
    name: "Modsec"
    needs: eligibility
    if: ${{ needs.eligibility.outputs.eligible == 'true' }}
    uses: ./.github/workflows/modsec-config.yml
    secrets: inherit

  deploy_qa:
    name: "Quality Control"
    if: ${{ needs.eligibility.outputs.eligible == 'true' }}
    uses: ./.github/workflows/deploy.yml
    needs: [eligibility, image, get_ip_ranges, modsec_config]
    with:
      environment: demo
      registry: ${{ needs.image.outputs.registry }}
      ips_formatted: ${{ needs.get_ip_ranges.outputs.ips_formatted }}
      modsec_config: ${{ needs.modsec_config.outputs.demo }}
    secrets: inherit
