name: Deploy to MoJ Cloud Platform

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  # Demo environment is scaled to, and hence does not need to be deployed
  # See README.md section: 'Deployment to Cloud Platform'
  DISABLE_DEMO_DEPLOY: "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: "Image"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  get_ip_ranges:
    name: "IP Ranges"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/ip-ranges-configure.yml
    secrets: inherit

  modsec_config:
    name: "Modsec"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/modsec-config.yml
    secrets: inherit

  deploy_dev:
    name: "Development"
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    needs: [image, get_ip_ranges, modsec_config]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
      ips_formatted: ${{ needs.get_ip_ranges.outputs.ips_formatted }}
      modsec_config: ${{ needs.modsec_config.outputs.development }}
    secrets: inherit

  deploy_staging:
    name: "Staging"
    needs: [image, deploy_dev, get_ip_ranges, modsec_config]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      registry: ${{ needs.image.outputs.registry }}
      ips_formatted: ${{ needs.get_ip_ranges.outputs.ips_formatted }}
      modsec_config: ${{ needs.modsec_config.outputs.staging }}
    secrets: inherit

  deploy_demo:
    name: "Demo"
    needs: [image, deploy_dev, get_ip_ranges, modsec_config]
    if: ${{ env.DISABLE_DEMO_DEPLOY != 'true' && github.event.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy.yml
    with:
      environment: demo
      registry: ${{ needs.image.outputs.registry }}
      ips_formatted: ${{ needs.get_ip_ranges.outputs.ips_formatted }}
      modsec_config: ${{ needs.modsec_config.outputs.demo }}
    secrets: inherit

  deploy_production:
    name: "Production"
    needs: [image, deploy_staging, get_ip_ranges, modsec_config]
    if: github.event.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
      ips_formatted: ${{ needs.get_ip_ranges.outputs.ips_formatted }}
      modsec_config: ${{ needs.modsec_config.outputs.production }}
    secrets: inherit
